#!/usr/bin/perl
#
# Connect to mqtt, wait for messages with sensor readings and write them into a rrd file
#

$configfile = "./mqttgraphd.conf";
$debug = 1;


if (!$debug) {
  use Proc::Daemon;
  $pid = Proc::Daemon::Init;
  exit if $pid;
}

use Config::Simple;

$cfg = new Config::Simple($configfile);

$mosquittohost = $cfg->param("mosquitto-host") ? $cfg->param("mosquitto-host") : "localhost";
$mqtttopic = $cfg->param("listen") ? $cfg->param("listen") : '+/#';

# open mosquitto and wait for messages to arrive

open(M,"mosquitto_sub -v -h $mosquittohost -t $mqtttopic |");

while (<M>) {
  my $start, $location, $type, $value;
  /^\/([^\/]+)\/(.*)\/(\S+) (.*)$/;
  print $_;

  $start = $1;
  $location = $2;
  $type = $3;
  $value = $4;

  $location =~ s/\//_/g;

  print "Start    = " . $start . "\n";
  print "Location = " . $location . "\n";
  print "Type     = " . $type . "\n";
  print "Value    = " . $value . "\n";
  
  # now composite the filename
  my $filename = $cfg->param("datadir") . "/" . $location . "-$type.rrd";
  print "$filename\n";

  # check if file not exists
  if (! -e $filename) {
    &createrrdfile($filename,$type);
  }

  # it exists but is not writable
  if (! -w $filename) {
    print STDERR "$filename is not writable\n";
    next;
  }

  # write value into rrd file
  print STDERR `rrdupdate $filename N:$value`;
}

sub createrrdfile {
  my $filename = shift;
  my $filetype = shift;

  my $createstring = $cfg->param("create-" . $filetype);
  if ($createstring ne "") {
    `rrdcreate $filename $createstring`;
    return 1;
  }
  return 0;
}
  




